Bug Fix: Add additionalTrustBundle defined CA Certificates from RHCOS CA Trust as a default
openshift/assisted-installer pull request #514
Opened 2022-08-02 02:23 UTC by kenmoini

Addresses Issue #513 

When additionalTrustBundle Root CA certificates are added to the RHCOS trusted store the assisted-installer-controller Job Pod needs to have them mounted - add the default `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` for CACertPath.

2022-08-04 18:41 UTC, mkowalski requested changes
Some test please? What if `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` does not exist and we try to mount it?

2022-08-04 20:11 UTC, kenmoini commented
> Some test please? What if `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` does not exist and we try to mount it?

Is there a configuration in which the assisted-installer-controller is not run in a Linux container or on a Linux host?

The `ca-certificates` package is a standard and required component of both the base images and RHCOS.  Curious if supportability of something like Mac OS X is targeted for out-of-cluster binary execution?

Anywho, happy to add a test or two for a discount-double-check...I can add a file/path check in `func NewExecutor` that resets that config variable to `""` if not found?  This would also provide a check and graceful failback for when a user specifies a different path that doesn't exist. 

Is there another test you'd like added otherwise?

2022-08-04 20:20 UTC, mkowalski commented
By no means I want to overengineer anything here especially that I see the use case as valid. I'm just worried about "what if", e.g. we have already had a case in the past where RHCOS didn't have the path you added - https://access.redhat.com/solutions/5582001.

> Curious if supportability of something like Mac OS X is targeted for out-of-cluster binary execution?
I wouldn't worry about this at all now. This is about running on the node that's part of OCP cluster, so as long as we install OCP on RHCOS this is the only thing we should care about. 

>I can add a file/path check in func NewExecutor that resets that config variable to "" if not found?

Yes please, something like this would make it already safer. I only want to make sure that we gracefully handle scenario when the file does not have the content you would expect it to have

2022-08-06 05:12 UTC, mkowalski commented
/ok-to-test
/test ?

2022-08-06 11:32 UTC, omertuc commented
/hold Not sure I entirely understand the issue/solution, but if anything the [defaulting](https://github.com/openshift/assisted-installer/blob/4b2e5c9319c59d46ee2572a0d8fc70cfda8ee318/src/config/config.go#L68) should happen at the installer which launches the controller, not at the controller itself

2022-08-10 17:16 UTC, eranco74 commented
@kenmoini please remove the default from the controllerConfig struct (just so we will have a single source of truth).

2022-09-16 14:53 UTC, mkowalski commented
/hold

Until I see something that ensures existence of `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`, I don't feel like this should land. RHCOS has this file **today**. Is it going to have it in the next release? Does FCOS have this file? Is it going to have it in the next release?

2022-09-16 15:59 UTC, kenmoini commented
> /hold
> 
> Until I see something that ensures existence of `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`, I don't feel like this should land. RHCOS has this file **today**. Is it going to have it in the next release? Does FCOS have this file? Is it going to have it in the next release?

Ok, where would you think the best place for the host filesystem check would be?  Leveraging *installer.ops.ExecPrivilegeCommand similar to how the finalize() func does?

2022-09-20 08:25 UTC, tsorya commented
will it be enough to validate this path exists on discovery iso?
actually i think we can always mount all /etc/pki as we do in agent and installer

2022-09-20 14:36 UTC, tsorya commented
@kenmoini i think we want to mount all the folder https://github.com/openshift/assisted-installer/pull/551

2022-09-21 08:41 UTC, omertuc commented
/close in favor of #551

2022-09-27 01:39 UTC, kenmoini commented
That should work too - thanks gang!

2022-09-27 01:39 UTC, closed without merging